### ISSUE TITLE
mingw compilation error: const CACHE_RELATIONSHIP' has no member named 'GroupCount

### ISSUE THREAD

**Issue by vtorri** [google/highway#2734]
when compiling on windows (msys2+mingw-w64), with contrib enabled, I have several error in topology.cc, like : 

```C:/Documents/msys2/home/vincent.torri/ewpi_64/share/ewpi/packages/highway/highway-1.3.0/hwy/contrib/thread_pool/topology.cc:710:24: error: 'const CACHE_RELATIONSHIP' has no member named 'GroupCount'```

**Comment by jan-wassenberg** [comment]
Thanks for reporting.
Windows SDK docs do not mention this field was added later, and potentially not even supported at runtime.
I've added a workaround. If we could rely on C++17 `if constexpr`, we could instead detect sizeof(Reserved) and if 20, then we don't access the field. But we're still supporting C++11 and I think it would be uglier to use SFINAE or CMake check_cxx_source_compiles (we now have a Meson build). Hence we're reading the value directly from memory.

Can you confirm #2739 fixes this?

**Comment by johnplatts** [comment]
@vtorri and @jan-wassenberg The issue is that you need to update the mingw-w64-ucrt-x86_64-headers-git, mingw-w64-clang-x86_64-headers-git, mingw-w64-x86_64-headers-git, mingw-w64-i686-headers-git, or mingw-w64-clang-aarch64-headers-git packages in your MSYS2 installation as there has been an update to mingw-w64-headers-git that adds the missing GroupCount and GroupMasks members to the CACHE_RELATIONSHIP and NUMA_NODE_RELATIONSHIP structures.

This issue was reported at https://github.com/mingw-w64/mingw-w64/issues/78 and fixed in commit https://github.com/mingw-w64/mingw-w64/commit/350d71bbeae38f283e68a87c1881451850882307 of mingw-w64.

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts , good to know MinGW headers have been updated. Still I think the issue remains that the OS might not have been updated to report GroupCount, so at the very least we'd still want the calloc and `HWY_MAX(1, count)` from #2739, right? Might as well do the whole thing to be completely independent of header/SDK version.
